version: "3.8"
services:
  ocproxy:
    privileged: true
    build: ./build
    env_file:
      - .env
    environment:
      OPENCONNECT_MFA_CODE: ${OPENCONNECT_MFA_CODE}
    ports:
      - 8888:8888
      - 8889:8889
    cap_add:
      - NET_ADMIN